Events-E1/Events.web/Controllers/AdminController.cs
using Events.web.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
namespace Events.web.Controllers
{
    [MyCustomAuthorize(Roles = "Administrator")] //Set role for admin only
    public class AdminController : BaseController //Announce class 'AdminController' from 'BaseController'
    {
        public ActionResult Trainer() //Publicly get action of 'Trainer' to set in other files
        {
            List<ApplicationUser> Trainers = new List<ApplicationUser>();
            var role = Db.Roles
                .Where(r => r.Name == "Trainer")
                .FirstOrDefault();
            if (role != null)
            {
                var users = Db.Users
                    .Where(u => u.Roles.Select(r => r.RoleId).Contains(role.Id))
                    .ToList();
                return View(users);
            }
            return View();
        }

        public ActionResult TrainingStaff() //Publicly get action of 'TrainingStaff' to set in other files
        {
            List<ApplicationUser> Trainers = new List<ApplicationUser>();
            var role = Db.Roles
                .Where(r => r.Name == "TrainingStaff")
                .FirstOrDefault();
            if (role != null)
            {
                var users = Db.Users
                    .Where(u => u.Roles.Select(r => r.RoleId).Contains(role.Id))
                    .ToList();
                return View(users);
            }
            return View();
        }

        [HttpGet] //Send data using a query string
        public ActionResult Edit(string id) //Publicly get action of 'Edit' to set in other files
        {
            var accountToEdit = this.Db.Users
                .Where(u => u.Id == id)
                .FirstOrDefault();
            if (accountToEdit == null)
            {
                var PreviousUrl = System.Web.HttpContext.Current.Request.UrlReferrer.ToString();
                return this.Redirect(PreviousUrl);
            }
            return this.View(accountToEdit);
        }

        [HttpPost] //Request method via Http page
        public ActionResult Edit(string id, ApplicationUser user) //Get 'Edit' action to set in other files
        {
            var accountToEdit = this.Db.Users
                .Where(u => u.Id == id)
                .FirstOrDefault();
            if (accountToEdit == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            if (user != null && this.ModelState.IsValid)
            {
                accountToEdit.FullName = user.FullName;
                accountToEdit.Age = user.Age;
                accountToEdit.DateofBirth = user.DateofBirth;
                accountToEdit.Education = user.Education;
                accountToEdit.ToeicScore = user.ToeicScore;
                accountToEdit.Location = user.Location;

                this.Db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return this.View(user);
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            var url = System.Web.HttpContext.Current.Request.UrlReferrer.ToString();
            var user = Db.Users.Find(id);
            if (user == null)
            {
                return Redirect(url);
            }
            Db.Users.Remove(user);
            var assign = Db.CoursesAssigned
                .Where(a => a.UserId == id)
                .ToList();
            if (assign != null)
            {
                foreach (var item in assign)
                {
                    Db.CoursesAssigned.Remove(item);
                }
            }
            Db.SaveChanges();
            return Redirect(url);
        }

        public ActionResult Role() //Publicly get 'Role' action to detail the role list
        {
            var Roles = Db.Roles.ToList();
            return View(Roles);
        }

        public ActionResult RoleCreate() //Publicly get 'RoleCreate' action to create new roles
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        [HttpPost] //Request method via Http page
        public ActionResult RoleCreate(IdentityRole Role) //Get 'RoleCreate' action to save into database
        {
            Db.Roles.Add(Role);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Events-E1/Events.web/Controllers/TrainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Events.web.Models;
using Microsoft.AspNet.Identity;

namespace Events.web.Controllers
{
    [MyCustomAuthorize(Roles = "Trainer , Trainee")]
    public class TrainController : BaseController
    {
        
        public ActionResult CourseAssigned()
        {
            List<Course> courses = new List<Course> { };
            var user = this.User.Identity.GetUserId();
            var course = Db.CoursesAssigned
                .Where(c => c.UserId == user)
                .Select(c => c.CourseId)
                .ToList();
            foreach (var id in course)
            {
                var c = Db.Courses
                    .Where(a => a.Id == id)
                    .FirstOrDefault();
                courses.Add(c);
            }
            return View(courses);
        }

        public ActionResult Course()
        {
            List<Course> courses = new List<Course> { };
            var courses1 = Db.Courses
                .OrderBy(e => e.Id)
                .ToList();
            foreach (var item in courses1)
            {
                var category = Db.CourseCategories
                    .Where(c => c.Id == item.CategoryId)
                    .FirstOrDefault();
                item.CourseCategory = category;
                courses.Add(item);
            }
            return View(courses);
        }
    }
}

Events-E1/Events.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AD_SP</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if ((User.IsInRole("Trainee")) || (User.IsInRole("Trainer")))
                    {
                        <li>@Html.ActionLink("My Course", "CourseAssigned", "Train")</li>
                        <li>@Html.ActionLink("Course List", "Course", "Train")</li>
                    }
                    @if (User.IsInRole("TrainingStaff"))
                    {
                        <li>@Html.ActionLink("Course List", "Course", "TrainingStaff")</li>
                        <li>@Html.ActionLink("Course Category", "Category", "TrainingStaff")</li>
                        <li>@Html.ActionLink("Trainee", "Trainee", "TrainingStaff")</li>
                        <li>@Html.ActionLink("Trainer", "Trainer", "TrainingStaff")</li>
                    }
                    @if (User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Training staff", "TrainingStaff", "Admin")</li>
                        <li>@Html.ActionLink("Trainer", "Trainer", "Admin")</li>
                        <li>@Html.ActionLink("Role List", "Role", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr>
        <footer>
            <p style="color:rgba(0, 0, 255, 0.6);">&copy; @DateTime.Now.Year - AD_SP Application</p>
        </footer>
    </div>
</body>
</html>